import { ApiResponse, ICart } from '~/services/interfaces'

export const blocks: ApiResponse = {
  data: [
    {
      id: '045019bb-06fc-4fa1-b703-318725b4d8af',
      displayId: '045019bb',
      createdAt: '2019-02-21T11:01:45.209Z',
      updatedAt: '2022-05-19T11:18:30.095702Z',
      createdBy: null,
      updatedBy: null,
      name: 'oneatlas-spot-aoiclipped',
      displayName: 'SPOT 6/7 Display (Streaming)',
      description: 'SPOT imagery in GeoTIFF format. RGB and panchromatic (1.5 m) bands.',
      provider: 'OneAtlas',
      type: 'DATA',
      metadata: {
        blockThumbnailUrl:
          'https://metadata.up42.com/045019bb-06fc-4fa1-b703-318725b4d8af/0_SPOT_6-7_Avatar1612547996375.jpg',
        pricingStrategy: {
          type: 'TILE_OUTPUT',
          credits: 3.0,
        },
        blockPricingStrategy: {
          name: 'simple',
          unit: 'TILE',
          direction: 'OUTPUT',
          credits: 3,
        },
      },
      version: '2.1.23',
      isPublic: true,
      isValid: true,
      isRestricted: false,
      isAccessGranted: true,
      isCreditPurchaseRequired: true,
      tags: [
        'Maritime',
        'Oil, Gas, Minerals, and Energy',
        'Optical',
        'Transportation',
        'Infrastructure and Utilities',
        'Satellite',
        'Insurance and Financial Services',
        'Environmental Protection',
        'Global',
        'Land Use and Management',
        'High Revisit',
        'Real Estate',
        'Agriculture',
      ],
      isPublicVersion: true,
      manifestVersion: 2,
    },
    {
      id: '3e146dd6-2b67-4d6e-a422-bb3d973e32ff',
      displayId: '3e146dd6',
      createdAt: '2019-02-21T11:02:11.535Z',
      updatedAt: '2021-05-06T08:47:26.525014Z',
      createdBy: null,
      updatedBy: null,
      name: 'tiling',
      displayName: 'Raster Tiling',
      description: 'Clips rasters into tiles for machine learning algorithms.',
      provider: 'UP42',
      type: 'PROCESSING',
      metadata: {
        blockThumbnailUrl:
          'https://metadata.up42.com/3e146dd6-2b67-4d6e-a422-bb3d973e32ff/Raster_Tiling_Thumbnail1608218469319.png',
        pricingStrategy: {
          type: 'MEGABYTE_INPUT',
          credits: 0.0,
        },
        blockPricingStrategy: {
          name: 'simple',
          unit: 'MEGABYTE',
          direction: 'INPUT',
          credits: 0,
        },
      },
      version: '2.2.8',
      isPublic: true,
      isValid: true,
      isRestricted: false,
      isAccessGranted: true,
      isCreditPurchaseRequired: false,
      tags: [
        'Maritime',
        'Oil, Gas, Minerals, and Energy',
        'Transportation',
        'Real Estate',
        'Raster',
        'Infrastructure and Utilities',
        'Sign-Up Credits',
        'Agriculture',
        'Insurance and Financial Services',
        'Environmental Protection',
        'Land Use and Management',
      ],
      isPublicVersion: true,
      manifestVersion: 2,
    },
  ],
}

export const cart: ICart = {
  '3e146dd6-2b67-4d6e-a422-bb3d973e32ff': {
    product: {
      id: '3e146dd6-2b67-4d6e-a422-bb3d973e32ff',
      displayId: '3e146dd6',
      createdAt: '2019-02-21T11:02:11.535Z',
      updatedAt: '2021-05-06T08:47:26.525014Z',
      createdBy: null,
      updatedBy: null,
      name: 'tiling',
      displayName: 'Raster Tiling',
      description: 'Clips rasters into tiles for machine learning algorithms.',
      provider: 'UP42',
      type: 'PROCESSING',
      metadata: {
        blockThumbnailUrl:
          'https://metadata.up42.com/3e146dd6-2b67-4d6e-a422-bb3d973e32ff/Raster_Tiling_Thumbnail1608218469319.png',
        pricingStrategy: { type: 'MEGABYTE_INPUT', credits: 0 },
        blockPricingStrategy: { name: 'simple', unit: 'MEGABYTE', direction: 'INPUT', credits: 0 },
      },
      version: '2.2.8',
      isPublic: true,
      isValid: true,
      isRestricted: false,
      isAccessGranted: true,
      isCreditPurchaseRequired: false,
      tags: [
        'Maritime',
        'Oil, Gas, Minerals, and Energy',
        'Transportation',
        'Real Estate',
        'Raster',
        'Infrastructure and Utilities',
        'Sign-Up Credits',
        'Agriculture',
        'Insurance and Financial Services',
        'Environmental Protection',
        'Land Use and Management',
      ],
      isPublicVersion: true,
      manifestVersion: 2,
    },
    quantity: 3,
  },
  '045019bb-06fc-4fa1-b703-318725b4d8af': {
    product: {
      id: '045019bb-06fc-4fa1-b703-318725b4d8af',
      displayId: '045019bb',
      createdAt: '2019-02-21T11:01:45.209Z',
      updatedAt: '2022-05-19T11:18:30.095702Z',
      createdBy: null,
      updatedBy: null,
      name: 'oneatlas-spot-aoiclipped',
      displayName: 'SPOT 6/7 Display (Streaming)',
      description: 'SPOT imagery in GeoTIFF format. RGB and panchromatic (1.5 m) bands.',
      provider: 'OneAtlas',
      type: 'DATA',
      metadata: {
        blockThumbnailUrl:
          'https://metadata.up42.com/045019bb-06fc-4fa1-b703-318725b4d8af/0_SPOT_6-7_Avatar1612547996375.jpg',
        pricingStrategy: { type: 'TILE_OUTPUT', credits: 3 },
        blockPricingStrategy: { name: 'simple', unit: 'TILE', direction: 'OUTPUT', credits: 3 },
      },
      version: '2.1.23',
      isPublic: true,
      isValid: true,
      isRestricted: false,
      isAccessGranted: true,
      isCreditPurchaseRequired: true,
      tags: [
        'Maritime',
        'Oil, Gas, Minerals, and Energy',
        'Optical',
        'Transportation',
        'Infrastructure and Utilities',
        'Satellite',
        'Insurance and Financial Services',
        'Environmental Protection',
        'Global',
        'Land Use and Management',
        'High Revisit',
        'Real Estate',
        'Agriculture',
      ],
      isPublicVersion: true,
      manifestVersion: 2,
    },
    quantity: 2,
  },
}
export const creditBalance = 1000
export const cartItemsCount = 4
